Add intermediate pointers to work around errors with nvhpc 22.7
See merge request icon/icon-nwp!825

The following minimal example can be used to trigger parts of the error that will be fixed with this MR.

```fortran
! nvfortran -O2 -ta=nvidia:cuda11.0 -Minfo -g -o routine_seq_type2 routine_seq_type2.f90
PROGRAM main
  TYPE particle
    REAL      :: x_max
  END TYPE particle

  INTEGER, PARAMETER :: a=1601
  REAL, DIMENSION(a) :: x
  INTEGER :: i
  TYPE(particle) :: cloud

  cloud%x_max = 1.

  !$acc data copy(cloud, x)
  CALL sub(cloud,x )
  !$acc end data

  print *, sum(x)

CONTAINS
  ELEMENTAL FUNCTION particle_meanmass(this) RESULT(xmean)
    !$ACC ROUTINE SEQ
    CLASS(particle), INTENT(in) :: this ! must be CLASS, as there are other types that inherit particle
    REAL                    :: xmean
    xmean = this%x_max
  END FUNCTION particle_meanmass

  SUBROUTINE sub(cloud, x)
    CLASS(particle), INTENT(IN) :: cloud
    REAL, INTENT(IN) :: x(:)
    INTEGER :: i, a

    a = SIZE(x)
    !$ACC PARALLEL DEFAULT(PRESENT)
    DO i = 1, a
      x(i) = particle_meanmass(cloud)
    ENDDO
    !$ACC END PARALLEL
  END SUBROUTINE sub

END PROGRAM main
```

The code above raises the following error. The same error was also triggered with the old ICON code version.
```
Error: segmentation violation, address not mapped to object
   rax 0x00007f3732f74c10, rbx 0x00007ffec8608d84, rcx 0x0000000000000002
   rdx 0x00007f3732f756a0, rsp 0x00007ffec8608ce0, rbp 0x00007ffec8608db0
   rsi 0x00007ffec8608d30, rdi 0x00007f3732d87fc8, r8  0x000000000000001c
   r9  0x000000000000001c, r10 0x00007ffec8608d30, r11 0x0000000000607180
   r12 0x00007ffec8608dc0, r13 0x0000000000000001, r14 0x0000000000607580
   r15 0x0000000000000000
  /lib64/libpthread.so.0(+0x168c0) [0x7f3730bab8c0]
  ./routine_seq_type2() [0x401373]
  /lib64/libc.so.6(__libc_start_main+0xef) [0x7f372ff4f29d]
```

The solution introduced with this MR is to change the subroutine sub code to:
```fortran
  SUBROUTINE sub(cloud_in, x)
    CLASS(particle), INTENT(IN), target :: cloud_in
    REAL, INTENT(IN) :: x(:)
    CLASS(particle), pointer :: cloud
    INTEGER :: i, a

    cloud => cloud_in ! ACCWA (nvhpc 22.7)
    a = SIZE(x)
    !$ACC PARALLEL DEFAULT(PRESENT)
    DO i = 1, a
      x(i) = particle_meanmass(cloud)
    ENDDO
    !$ACC END PARALLEL
  END SUBROUTINE sub
```

In addition the the pointer, `ACC WAIT` has to be added before the end of the subroutine. Otherwise the asynchronous mode crashes with "call to cuStreamSynchronize(after launch) returned error 700: Illegal address during kernel execution" (nhvpc 22.7 and 22.3).

The additional pointers and WAITs make the microphysics runs slower on Daint. With only one compute process the `exp.mch_opr_r19b07_2m` experiment took 0.18s before and 0.25s after this MR.

Approved-by: Daniel Reinert <daniel.reinert@dwd.de>
Merged-by: Daniel Reinert <daniel.reinert@dwd.de>